version: "3.3"

services:
    web:
        container_name: ${CONTAINER_NAME}
        build:
            dockerfile: .docker/Dockerfile
            context: ..
            args:
                - USERNAME=${USERNAME:-ubuntu}
                - UID=${UID:-1000}
                - GROUP=${GROUP:-root}
                - ROOTPASS=${ROOTPASS:-l3tm31n}
                - INSTALL_NODE=${INSTALL_NODE-true}
                - INSTALL_COMPOSER=${INSTALL_COMPOSER-true}
        expose:
            - "${WEB_PORT:-80}"
            - "${VITE_PORT:-5173}"
        volumes:
            - ../:/var/www
        extra_hosts:
            - host.docker.internal:host-gateway
        links:
            - db
            - redis
            - mailpit
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.${CONTAINER_NAME}.rule=Host(`${DOMAIN}`)"
            - "traefik.http.routers.${CONTAINER_NAME}.entrypoints=${ENTRYPOINT}"
            - "traefik.http.routers.${CONTAINER_NAME}.service=${CONTAINER_NAME}"
            - "traefik.http.services.${CONTAINER_NAME}.loadbalancer.server.port=${WEB_PORT:-80}"
            - "traefik.http.routers.${CONTAINER_NAME}.tls=${TLS:-false}"
            - "traefik.http.routers.${CONTAINER_NAME}.tls.certresolver=${CERT_RESOLVER:-letsencrypt}"
            - "traefik.http.routers.${CONTAINER_NAME}-vite.entrypoints=${ENTRYPOINT_VITE}"
            - "traefik.http.routers.${CONTAINER_NAME}-vite.rule=Host(`${DOMAIN}`)"
            - "traefik.http.routers.${CONTAINER_NAME}-vite.service=${CONTAINER_NAME}-vite"
            - "traefik.http.services.${CONTAINER_NAME}-vite.loadbalancer.server.port=${VITE_PORT:-5173}"
            - "traefik.http.routers.${CONTAINER_NAME}-vite.tls=${TLS:-false}"
            - "traefik.http.routers.${CONTAINER_NAME}-vite.tls.certresolver=${CERT_RESOLVER:-letsencrypt}"
        networks:
            - proxy
        tty: true

    db:
        container_name: "${CONTAINER_NAME}-db"
        image: mysql
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD:-l3tm31n}"
        expose:
            - "${MYSQL_PORT:-3306}"
        ports:
            - "${MYSQL_EXTERNAL_PORT:-33060}:3306"
        volumes:
            - ./docker_volumes/db:/var/lib/mysql
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.${CONTAINER_NAME}-db.entrypoints=${ENTRYPOINT_DB}"
            - "traefik.http.routers.${CONTAINER_NAME}-db.rule=Host(`db.${DOMAIN}`)"
            - "traefik.http.routers.${CONTAINER_NAME}-db.service=${CONTAINER_NAME}-db"
            - "traefik.http.services.${CONTAINER_NAME}-db.loadbalancer.server.port=${MYSQL_PORT:-3306}"
            - "traefik.http.routers.${CONTAINER_NAME}-db.tls=${DB_TLS:-false}"
            - "traefik.http.routers.${CONTAINER_NAME}-db.tls.certresolver=${CERT_RESOLVER:-letsencrypt}"
        networks:
            - proxy

    phpmyadmin:
        container_name: "${CONTAINER_NAME}-pma"
        image: phpmyadmin/phpmyadmin:latest
        expose:
            - "${PHPMYADMIN_PORT:-80}"
        depends_on:
            - db
        links:
            - db
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.${CONTAINER_NAME}-pma.entrypoints=${ENTRYPOINT}"
            - "traefik.http.routers.${CONTAINER_NAME}-pma.rule=Host(`pma.${DOMAIN}`)"
            - "traefik.http.routers.${CONTAINER_NAME}-pma.service=${CONTAINER_NAME}-pma"
            - "traefik.http.services.${CONTAINER_NAME}-pma.loadbalancer.server.port=${PHPMYADMIN_PORT:-80}"
            - "traefik.http.routers.${CONTAINER_NAME}-pma.tls=${TLS:-false}"
            - "traefik.http.routers.${CONTAINER_NAME}-pma.tls.certresolver=${CERT_RESOLVER:-letsencrypt}"
        networks:
            - proxy

    redis:
        image: "redis:alpine"
        container_name: "${CONTAINER_NAME}-redis"
        expose:
            - "${REDIS_PORT:-6379}"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.${CONTAINER_NAME}-redis.rule=Host(`redis.${DOMAIN}`)"
            - "traefik.http.routers.${CONTAINER_NAME}-redis.entrypoints=${ENTRYPOINT}"
        networks:
            - proxy

    mailpit:
        image: "axllent/mailpit:latest"
        container_name: "${CONTAINER_NAME}-mailpit"
        environment:
            MP_UI_BIND_ADDR: "0.0.0.0:${MAILPIT_PORT:-80}"
        expose:
            - "${MAILPIT_PORT:-80}"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.${CONTAINER_NAME}-mailpit.entrypoints=${ENTRYPOINT}"
            - "traefik.http.routers.${CONTAINER_NAME}-mailpit.rule=Host(`mailpit.${DOMAIN}`)"
            - "traefik.http.routers.${CONTAINER_NAME}-mailpit.service=${CONTAINER_NAME}-mailpit"
            - "traefik.http.services.${CONTAINER_NAME}-mailpit.loadbalancer.server.port=${MAILPIT_PORT:-80}"
            - "traefik.http.routers.${CONTAINER_NAME}-mailpit.tls=${TLS:-false}"
            - "traefik.http.routers.${CONTAINER_NAME}-mailpit.tls.certresolver=${CERT_RESOLVER:-letsencrypt}"
        networks:
            - proxy

    typesense:
        image: 'typesense/typesense:27.1'
        ports:
            - '${FORWARD_TYPESENSE_PORT:-8108}:8108'
        environment:
            TYPESENSE_DATA_DIR: '${TYPESENSE_DATA_DIR:-/typesense-data}'
            TYPESENSE_API_KEY: '${TYPESENSE_API_KEY:-xyz}'
            TYPESENSE_ENABLE_CORS: '${TYPESENSE_ENABLE_CORS:-true}'
        volumes:
            - ./docker_volumes/typesense:/typesense-data
        networks:
            - proxy

networks:
    proxy:
        external: true
